server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://yxs.yang-xiansen.top:3306/white_jotter?characterEncoding=UTF-8
    username: white_jotter
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
