server:
  port: 8904
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git: #配置存储配置信息的Git仓库
          uri: https://gitee.com/yangxianshen/springcloud-config
          username: yxs
          password: 123456
          clone-on-start: true #开启启动时直接从git获取配置
  rabbitmq:
    host: localhost
    port: 5672
    username: yxs
    password: 123456
    virtual-host: /
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'
