security:
  basic:
    enabled: true

server:
  servlet:
    session:
      timeout: 3600
spring:
  session:
    # session存储位置
    store-type: redis

      #redis
  redis:
    # Redis数据库索引（默认为0）
    database: 2
    # Redis服务器地址
    host: yxs.yang-xiansen.top
    # Redis服务器连接端口
    port: 6379
    # 密码
    password: 123456
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 5000
#  main:
#    allow-bean-definition-overriding: true
