server:
  port: 8401
spring:
  application:
    name: consul-ribbon-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery: ${spring.application.name}

service-url:
  user-service: http://consul-user-service
