server:
  port: 8905
spring:
  application:
    name: config-security-server

  security: #配置用户名和密码
    user:
      name: yxs
      password: 123456

  cloud:
    config:
      server:
        git: #配置存储配置信息的Git仓库
          uri: https://gitee.com/yangxianshen/springcloud-config
          username: yxs
          password: 123456
          clone-on-start: true #开启启动时直接从git获取配置
#          search-paths: '{application}'  用于搜索子目录中的配置
