management:
  endpoints:
    web:
      exposure:
        #开启所有页面节点 默认只开启health info两个点  boot2.0弃用 management.security.enabled
        include: '*'
  endpoint:
    health:
      show-details: always #详细

server:
  port: 8081

spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8080/admin-server
